model:
  backbone:
    backbone_type: R50
  RPN:
    train_region_threshold: 0.7

data_loader:
  data_dir: data/coco
  
  # annotation file should have json format
  train_instance: annotations/instances_train2017.json
  val_instance: annotations/instances_val2017.json
  train_data: train2017
  val_data: val2017
  test_data: test2017

  resize: 1024
  batch_size: 2
  num_workers: 2
  train_shuffle: true
  val_shuffle: false

train:
  max_epoch: 128
  optimizer: Adam
  lr: 1.0e-4


  