data_loader:
  data_dir: data/coco
  
  # annotation file should have json format
  train_instance: annotations/instances_train2017.json
  val_instance: annotations/instances_val2017.json
  test_instance: annotations/image_info_test2017.json
  train_data: train2017
  val_data: val2017
  test_data: test2017

  input_size: [1024, 1024]
  batch_size: 8
  num_workers: 4

train:
  RPN_cls_loss_weight: 1
  RPN_box_loss_weight: 1
  max_epoch: 36
  optimizer: SGD
  lr: 0.01
  checkpoint_dir: data/saved/checkpoint
